
### ENV EXPLANATION: https://github.com/camunda/docker-camunda-bpm-platform ###
env:
  DB_DRIVER: "org.postgresql.Driver"
  # SPRING_DATASOURCE_URL: "jdbc:postgresql://pgdb-postgresql:5432/process-engine"
  # SPRING_DATASOURCE_USERNAME: postgres
  # SPRING_DATASOURCE_PASSWORD: postgres
  # DB_CONN_MAXACTIVE: 20
  # DB_CONN_MAXIDLE: 20
  # DB_CONN_MINIDLE: 5
  DB_URL: "jdbc:postgresql://psql-postgresql:5432/camunda_db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  # DB_VALIDATE_ON_BORROW: "true"
  # DB_VALIDATION_QUERY: SELECT 1
  # DB_PASSWORD_FILE:
  # SKIP_DB_CONFIG: true
  WAIT_FOR: "psql-postgresql:5432"
  # WAIT_FOR_TIMEOUT: 30
