apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camunda-bpm
  name: camunda-bpm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: platform
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: camunda-bpm
        app.kubernetes.io/component: platform
    spec:
      containers:
      - image: {{ .Values.image }}
        name: camunda-bpm
        envFrom:
          - configMapRef:
              name: camunda-env
        ports:
        - containerPort: 8080
          name: http
