apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camunda-bpm
  name: camunda-bpm
spec:
  selector:
    matchLabels:
      app: camunda-bpm
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: camunda-bpm
    spec:
      containers:
      - image: {{ .Values.image }}
        name: camunda-bpm
        envFrom:
          - configMapRef:
              name: camunda-env
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9404
          name: metrics
        readinessProbe:
          httpGet:
            path: /camunda
            port: http
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/config/
          name: config
      volumes:
      - configMap:
          defaultMode: 484
          name: prom-config
        name: config
