apiVersion: v1
kind: Service
metadata:
  labels:
    app: camunda-bpm
  name: camunda-bpm-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: camunda-bpm
  type: ClusterIP
