apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: camunda-bpm
  name: jmx
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app: camunda-bpm
